name: CI - Unit tests

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  php-tests:
    name: Lumen (PHPUnit)
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: energeX_test
          MYSQL_AUTHENTICATION_PLUGIN: mysql_native_password
        ports: ["3306:3306"]
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -proot --silent"
          --health-interval=5s --health-timeout=3s --health-retries=30

    steps:
      - uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: mbstring, intl, pdo_mysql
          coverage: none

      - name: Install Composer deps (cached)
        working-directory: lumen-api
        run: composer install --prefer-dist --no-interaction --no-progress

      # Wait for MySQL and create a dedicated CI user with DB grants
      - name: Create CI DB user
        run: |
          sudo apt-get update -y
          sudo apt-get install -y mysql-client
          for i in {1..30}; do
            mysql -h 127.0.0.1 -P 3306 -uroot -proot -e "SELECT 1" && break || sleep 1
          done
          mysql -h 127.0.0.1 -P 3306 -uroot -proot <<'SQL'
          CREATE USER IF NOT EXISTS 'ci'@'%' IDENTIFIED BY 'ci';
          GRANT ALL PRIVILEGES ON `energeX_test`.* TO 'ci'@'%';
          FLUSH PRIVILEGES;
          SQL

      - name: Prepare env files for CI
        working-directory: lumen-api
        run: |
          cp .env.testing .env || true
          for f in .env .env.testing; do
            grep -q '^DB_CONNECTION=' "$f" && sed -i 's/^DB_CONNECTION=.*/DB_CONNECTION=mysql/' "$f" || echo 'DB_CONNECTION=mysql' >> "$f"
            grep -q '^DB_HOST=' "$f"       && sed -i 's/^DB_HOST=.*/DB_HOST=127.0.0.1/' "$f"      || echo 'DB_HOST=127.0.0.1' >> "$f"
            grep -q '^DB_PORT=' "$f"       && sed -i 's/^DB_PORT=.*/DB_PORT=3306/' "$f"           || echo 'DB_PORT=3306' >> "$f"
            grep -q '^DB_DATABASE=' "$f"   && sed -i 's/^DB_DATABASE=.*/DB_DATABASE=energeX_test/' "$f" || echo 'DB_DATABASE=energeX_test' >> "$f"
            grep -q '^DB_USERNAME=' "$f"   && sed -i 's/^DB_USERNAME=.*/DB_USERNAME=ci/' "$f"     || echo 'DB_USERNAME=ci' >> "$f"
            grep -q '^DB_PASSWORD=' "$f"   && sed -i 's/^DB_PASSWORD=.*/DB_PASSWORD=ci/' "$f"     || echo 'DB_PASSWORD=ci' >> "$f"
          done
          # JWT secret (fallback if secret not set)
          echo "JWT_SECRET=${{ secrets.CI_JWT_SECRET || 'testing_jwt_secret_please_override' }}" >> .env
          echo "JWT_SECRET=${{ secrets.CI_JWT_SECRET || 'testing_jwt_secret_please_override' }}" >> .env.testing

      - name: Run migrations (retry a bit)
        working-directory: lumen-api
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: energeX_test
          DB_USERNAME: ci
          DB_PASSWORD: ci
          APP_ENV: testing
        run: |
          for i in {1..5}; do
            php artisan migrate --force && break || { echo "migrate retry $i"; sleep 3; }
          done

      - name: Run PHPUnit
        working-directory: lumen-api
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: energeX_test
          DB_USERNAME: ci
          DB_PASSWORD: ci
          APP_ENV: testing
          CACHE_DRIVER: array
          QUEUE_CONNECTION: sync
        run: vendor/bin/phpunit --colors=always

  node-tests:
    name: Node cache (Jest)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: node-cache-service/package-lock.json
      - name: Install deps
        working-directory: node-cache-service
        run: npm ci
      - name: Run tests
        working-directory: node-cache-service
        run: npm test -- --color
